/**
 * Downloads the book covers from the publisher's public site into
 * public/covers/ and rewrites src/data/covers.ts with the files that were
 * actually saved. Run it once before a demo so the prototype never depends on
 * the remote server:
 *
 *   node scripts/download-covers.mjs
 *
 * Anything that fails is reported and simply left out of the manifest, so the
 * app falls back to the remote URL and then to a typographic cover. It never
 * substitutes one cover for another.
 */
import fs from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const outDir = path.join(root, "public", "covers");

async function readBooks() {
  const files = ["src/data/books.ts", "src/data/books-secundaria.ts"];
  const base = "https://stanfordpublishing.com.mx/wp-content/uploads";
  const entries = [];
  for (const file of files) {
    const src = await fs.readFile(path.join(root, file), "utf8");
    const re = /slug:\s*"([^"]+)"[\s\S]*?cover:\s*`\$\{U\}([^`]+)`/g;
    let m;
    while ((m = re.exec(src))) entries.push({ slug: m[1], url: base + m[2] });
  }
  return entries;
}

const books = await readBooks();
await fs.mkdir(outDir, { recursive: true });

const saved = {};
const failed = [];

for (const book of books) {
  const ext = path.extname(new URL(book.url).pathname) || ".png";
  const filename = `${book.slug}${ext}`;
  try {
    const res = await fetch(book.url, { headers: { "User-Agent": "Mozilla/5.0" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const buffer = Buffer.from(await res.arrayBuffer());
    if (buffer.byteLength < 1024) throw new Error("archivo demasiado pequeño");
    await fs.writeFile(path.join(outDir, filename), buffer);
    saved[book.slug] = `/covers/${filename}`;
    console.log(`ok    ${book.slug}`);
  } catch (error) {
    failed.push({ slug: book.slug, reason: String(error.message ?? error) });
    console.warn(`falló ${book.slug} — ${error.message ?? error}`);
  }
}

const manifest = `/**
 * Local cover files present in /public/covers, keyed by book slug.
 * Generated by scripts/download-covers.mjs — do not edit by hand.
 */
export const localCovers: Record<string, string> = ${JSON.stringify(saved, null, 2)};
`;
await fs.writeFile(path.join(root, "src", "data", "covers.ts"), manifest);

console.log(`\n${Object.keys(saved).length} portadas guardadas, ${failed.length} sin confirmar.`);
if (failed.length) {
  await fs.writeFile(
    path.join(root, "covers-pendientes.json"),
    JSON.stringify(failed, null, 2)
  );
  console.log("Lista de pendientes: covers-pendientes.json");
}
