/**
 * Compresses the downloaded covers so the demo stays fast on a phone.
 *
 *   node scripts/optimize-covers.mjs
 *
 * Rewrites every file in public/covers/ as WebP, max 600px wide (the grid never
 * shows them larger). Originals are moved to public/covers/original/ so nothing
 * is lost, and src/data/covers.ts is updated to the new filenames.
 */
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const root = path.resolve(import.meta.dirname, "..");
const dir = path.join(root, "public", "covers");
const backup = path.join(dir, "original");

const MAX_WIDTH = 600;
const QUALITY = 82;

await fs.mkdir(backup, { recursive: true });

const files = (await fs.readdir(dir, { withFileTypes: true }))
  .filter((f) => f.isFile() && /\.(png|jpe?g)$/i.test(f.name))
  .map((f) => f.name);

if (files.length === 0) {
  console.log("No hay portadas que optimizar. Ejecuta antes: npm run covers");
  process.exit(0);
}

const manifest = {};
let before = 0;
let after = 0;

for (const file of files) {
  const source = path.join(dir, file);
  const slug = path.basename(file, path.extname(file));
  const target = path.join(dir, `${slug}.webp`);

  const stat = await fs.stat(source);
  before += stat.size;

  await sharp(source)
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toFile(target);

  const out = await fs.stat(target);
  after += out.size;

  await fs.rename(source, path.join(backup, file));
  manifest[slug] = `/covers/${slug}.webp`;
  console.log(`  ${slug}  ${(stat.size / 1024).toFixed(0)} KB -> ${(out.size / 1024).toFixed(0)} KB`);
}

const contents = `/**
 * Local cover files present in /public/covers, keyed by book slug.
 * Generated by scripts/download-covers.mjs and scripts/optimize-covers.mjs.
 */
export const localCovers: Record<string, string> = ${JSON.stringify(manifest, null, 2)};
`;
await fs.writeFile(path.join(root, "src", "data", "covers.ts"), contents);

const mb = (n) => (n / 1024 / 1024).toFixed(1);
console.log(
  `\n${files.length} portadas: ${mb(before)} MB -> ${mb(after)} MB ` +
    `(${Math.round((1 - after / before) * 100)}% menos).`
);
console.log("Originales guardados en public/covers/original/ (añádelo a .gitignore si no los quieres versionar).");
